[build-system]
# setuptools is a default requirement, but pyshortcuts is needed to create shortcuts after install
# wheel should be part of setuptools...but...not!
requires = ["setuptools", "pyshortcuts", "wheel"]
build-backend = "setuptools.build_meta"
